import type { NextPage } from 'next';
import Head from 'next/head';
import { Menu } from '../components/menu';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bike Rentals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu>
        <h1>Welcome</h1>
        <p>This is a simple app for bike rental</p>
      </Menu>
    </div>
  );
};

export default Home;
